
TYPE
	MaqEstados_enum : 
		(
		HTTP_STEP_DESABILITADO := 0,
		HTTP_STEP_CONCATENA,
		HTTP_STEP_ENVIA,
		HTTP_STEP_DELAY,
		HTTP_STEP_PROXIMO_DG,
		HTTP_STEP_CONCLUIDO,
		HTTP_STEP_ABORTA,
		HTTP_STEP_ERRO
		);
END_TYPE
